<?xml version="1.0" encoding="UTF-8"?>
<testExecutions version="1">
  <file path="D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\build\src\test\database\connection.test.js">
    <testCase name="Database Test connection" duration="399"/>
  </file>
  <file path="D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\src\test\database\connection.test.ts">
    <testCase name="Database Test connection" duration="295"/>
  </file>
  <file path="D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\build\src\test\api\users.test.js">
    <testCase name="Users Create user response 201 if success" duration="65">
      <failure message="Error: expected 201 &quot;Created&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 201 "Created", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user password 400 if email field is empty" duration="26">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password field is empty" duration="26">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if username field is empty" duration="28">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if email is invalid" duration="24">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password is less than 4 letter" duration="23">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password is greater than 20 letter" duration="22">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Get user response 200 with list of users when get all users" duration="51">
      <failure message="Error: expected 200 &quot;OK&quot;, got 403 &quot;Forbidden&quot;"><![CDATA[Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
  </file>
  <file path="D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\src\test\api\users.test.ts">
    <testCase name="Users Create user response 201 if success" duration="61">
      <failure message="Error: expected 201 &quot;Created&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 201 "Created", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user password 400 if email field is empty" duration="21">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password field is empty" duration="31">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if username field is empty" duration="23">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if email is invalid" duration="22">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password is less than 4 letter" duration="25">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Create user response 400 if password is greater than 20 letter" duration="23">
      <failure message="Error: expected 400 &quot;Bad Request&quot;, got 404 &quot;Not Found&quot;"><![CDATA[Error: expected 400 "Bad Request", got 404 "Not Found"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
    <testCase name="Users Get user response 200 with list of users when get all users" duration="48">
      <failure message="Error: expected 200 &quot;OK&quot;, got 403 &quot;Forbidden&quot;"><![CDATA[Error: expected 200 "OK", got 403 "Forbidden"
    at Test.Object.<anonymous>.Test._assertStatus (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:268:12)
    at Test.Object.<anonymous>.Test._assertFunction (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:283:11)
    at Test.Object.<anonymous>.Test.assert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:173:18)
    at Server.localAssert (D:\mystudy-material\eIRed-todo-Ass\node-assingment-todo-final-2 (1)\node-assingment-todo\node_modules\supertest\lib\test.js:131:12)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitCloseNT (node:net:1880:8)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)]]></failure>
    </testCase>
  </file>
</testExecutions>